export const IS_FETCHD_IMAGE_CATEGORY = "IS_FETCHD_IMAGE_CATEGORY";
export const GET_SINGLE_IMAGE_CONTENT = "GET_SINGLE_IMAGE_CONTENT";
export const UPLOAD_TARGET_IMAGE = "UPLOAD_TARGET_IMAGE";
export const TOGGLE_REPORTBUG_VISIBILITY = "TOGGLE_REPORTBUG_VISIBILITY";
export const SET_CURRENT_IMAGE_CATEGORY = "SET_CURRENT_IMAGE_CATEGORY";
