export const FETCHD_IMAGE_CATEGORY = "IS_FETCHD_IMAGE_CATEGORY";
export const UPLOAD_TARGET_IMAGE = "UPLOAD_TARGET_IMAGE";
export const SET_SOURCE_IMAGE = "SET_SOURCE_IMAGE";
export const TOGGLE_REPORTBUG_VISIBILITY = "TOGGLE_REPORTBUG_VISIBILITY";
export const TOGGLE_REVIEW_VISIBILITY = "TOGGLE_REVIEW_VISIBILITY";
export const TOGGLE_SHARE_VISIBILITY = "TOGGLE_SHARE_VISIBILITY";
export const IS_UPLOAD_INPUTS_EXPANDED = "IS_UPLOAD_INPUTS_EXPANDED";
