export const FETCHD_IMAGE_CATEGORY = "IS_FETCHD_IMAGE_CATEGORY";
export const UPLOAD_TARGET_IMAGE = "UPLOAD_TARGET_IMAGE";
export const TOGGLE_REPORTBUG_VISIBILITY = "TOGGLE_REPORTBUG_VISIBILITY";
export const TOGGLE_REVIEW_VISIBILITY = "TOGGLE_REVIEW_VISIBILITY";
